DataDashboardWeb/Pages/ApplyFilters.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;

namespace DataDashboardWeb.Pages
{
    public class ApplyFiltersModel : PageModel
    {
        public string Message { get; set; }
        public List<DataFilter> Geographies { get; set; }
        public List<DataFilter> Industries { get; set; }
        public List<DataFilter> CompanySizes { get; set; }

        public void OnGet()
        {
            /*
            CHANGE:
            (9-5-2018)

            To reduce the number of filters the Values property has been added to the DataFilter class
            This allows a single option to represent multiple actual filter options
            For example, "Small" organisation size can include filter options 1,2,3,4
            Previously the Id property was used
            To make this work, the Ids have been changed so that they are unique across ALL filters
            Instead of only unique within a specific filter

            As a result, we have to hold each filter in two session variables:
            One holds IDs for checking filter options when this screen loads
            Two holds the actual values that get passed to the API

            -- Original Geographies, Industries and CompanySizes can be found at the bottom of this file --

            */

            LoadDataFilters();

            // Now, if we have any filters set let's assign them
            CheckExistingFilters(Geographies);
            CheckExistingFilters(Industries);
            CheckExistingFilters(CompanySizes);
        }

        private void LoadDataFilters()
        {
            Geographies = new List<DataFilter>()
            {
                new DataFilter() { Id = 100, Values = "1", Name = "Asia Pacific", Indent = 0, IsSelected = false },
                new DataFilter() { Id = 101, Values = "3", Name = "EMEA", Indent = 0, IsSelected = false },
                new DataFilter() { Id = 102, Values = "29", Name = "United Kingdom", Indent = 1, IsSelected = false },
                new DataFilter() { Id = 103, Values = "14,15,16,17,19,20,7,23,24,26,27,28", Name = "Rest of EMEA", Indent = 1, IsSelected = false },
                new DataFilter() { Id = 104, Values = "4", Name = "North America", Indent = 0, IsSelected = false },
                new DataFilter() { Id = 105, Values = "5", Name = "South America", Indent = 0, IsSelected = false }
            };

            Industries = new List<DataFilter>()
            {
                new DataFilter() { Id = 200, Values = "3", Name = "Chemicals and Petroleum", Indent = 0, IsSelected = false },
                new DataFilter() { Id = 201, Values = "4", Name = "Consultancies and Professional Services", Indent = 0, IsSelected = false },
                new DataFilter() { Id = 202, Values = "8", Name = "Financial Services", Indent = 0, IsSelected = false },
                new DataFilter() { Id = 203, Values = "9,1,5,6,10", Name = "Government (defence, education, health, utils)", Indent = 0, IsSelected = false },
                new DataFilter() { Id = 204, Values = "12,2", Name = "Manufacturing, Construction and Engineering", Indent = 0, IsSelected = false },
                new DataFilter() { Id = 205, Values = "13", Name = "Media, Entertainment and Gaming", Indent = 0, IsSelected = false },
                new DataFilter() { Id = 206, Values = "7,14", Name = "Retail and Consumer Goods", Indent = 0, IsSelected = false },
                new DataFilter() { Id = 207, Values = "11", Name = "Software", Indent = 0, IsSelected = false },
                new DataFilter() { Id = 208, Values = "15", Name = "Telecommunications", Indent = 0, IsSelected = false },
                new DataFilter() { Id = 209, Values = "16", Name = "Transport and Logistics", Indent = 0, IsSelected = false }
            };

            CompanySizes = new List<DataFilter>()
            {
                new DataFilter() { Id = 300, Values = "1,2,3,4", Name = "Less than 1000 employees", Indent = 0, IsSelected = false },
                new DataFilter() { Id = 301, Values = "5,6", Name = "1,000 – 25,000 employees", Indent = 0, IsSelected = false },
                new DataFilter() { Id = 302, Values = "7", Name = "More than 25,000 employees", Indent = 0, IsSelected = false }
            };
        }

        public IActionResult OnPostApply()
        {
            // Get the selected filters (if any)
            // This gives us the IDs, not the actual values
            string geographies = Request.Form["chkgeography"].ToString();
            string industries = Request.Form["chkindustry"].ToString();
            string companySizes = Request.Form["chkcompanysize"].ToString();

            // Get the page that we need to postback to
            string postbackPage = Request.Form["postbackPage"];

            // Save the Ids for use when/if this page is re-opened (to preselect checkboxes)
            List<int> Ids = new List<int>();
            if (string.IsNullOrWhiteSpace(geographies) == false) Ids.AddRange(geographies.Split(',').Select(int.Parse).ToList());
            if (string.IsNullOrWhiteSpace(industries) == false) Ids.AddRange(industries.Split(',').Select(int.Parse).ToList());
            if (string.IsNullOrWhiteSpace(companySizes) == false) Ids.AddRange(companySizes.Split(',').Select(int.Parse).ToList());
            HttpContext.Session.SetString("Filters", string.Join(",", Ids.ToArray())); // Save to session as comma separated string

            // Convert IDs into values
            LoadDataFilters();

            geographies = GetValues(geographies, Geographies);
            industries = GetValues(industries, Industries);
            companySizes = GetValues(companySizes, CompanySizes);

            // Now, assign these to our session
            HttpContext.Session.SetString("Geographies", geographies);
            HttpContext.Session.SetString("Industries", industries);
            HttpContext.Session.SetString("CompanySizes", companySizes);

            if (string.IsNullOrWhiteSpace(postbackPage))
            {
                postbackPage = "DashboardHome";
            }

            return Redirect(postbackPage);
        }

        public IActionResult OnPostClear()
        {
            // Clear all filters
            HttpContext.Session.SetString("Geographies", string.Empty);
            HttpContext.Session.SetString("Industries", string.Empty);
            HttpContext.Session.SetString("CompanySizes", string.Empty);
            HttpContext.Session.SetString("Filters", string.Empty);

            // Get the page that we need to postback to
            string postbackPage = Request.Form["postbackPage"];

            if (string.IsNullOrWhiteSpace(postbackPage))
            {
                postbackPage = "DashboardHome";
            }

            return Redirect(postbackPage);
        }

        private void CheckExistingFilters(List<DataFilter> dataFilters)
        {
            // This method was changed as part of the 9-5-18 change
            // Check to see if any filters have already been set
            // If so then make sure they are checked when the form loads
            string filters = string.Empty;

            if (HttpContext.Session.GetString("Filters") != null) filters = HttpContext.Session.GetString("Filters");

            string[] ids;

            if (string.IsNullOrWhiteSpace(filters) == false)
            {
                ids = filters.Split(',');
                foreach (string id in ids)
                {
                    foreach (var item in dataFilters)
                    {
                        if (id == item.Id.ToString())
                        {
                            item.IsSelected = true;
                        }
                    }
                }
            }
        }

        private string GetValues(string filter, List<DataFilter> dataFilters)
        {
            // Convert a list of Ids into a list of Values
            string values = string.Empty;
            string[] ids;

            if (string.IsNullOrWhiteSpace(filter) == false)
            {
                ids = filter.Split(',');
                foreach (string id in ids)
                {
                    foreach (var item in dataFilters)
                    {
                        if (id == item.Id.ToString())
                        {
                            values = values + item.Values + ",";
                        }
                    }
                }

                values = values.Substring(0, values.Length - 1); // strip the last ','
            }

            return values;
        }
    }

    public class DataFilter
    {
        public int Id { get; set; }
        public string Values { get; set; }
        public string Name { get; set; }
        public int Indent { get; set; }
        public bool IsSelected { get; set; }
    }
}

/*
Geographies = new List<DataFilter>()
{
    new DataFilter() { Id = 1, Values = "1", Name = "Asia Pacific", Indent = 0, IsSelected = false },
    new DataFilter() { Id = 2, Values = "2", Name = "Australia", Indent = 1, IsSelected = false },
    new DataFilter() { Id = 13, Values = "13", Name = "China", Indent = 1, IsSelected = false },
    new DataFilter() { Id = 18, Values = "18", Name = "India", Indent = 1, IsSelected = false },
    new DataFilter() { Id = 21, Values = "21", Name = "Japan", Indent = 1, IsSelected = false },
    new DataFilter() { Id = 25, Values = "25", Name = "South Korea", Indent = 1, IsSelected = false },
    new DataFilter() { Id = 3, Values = "3", Name = "EMEA", Indent = 0, IsSelected = false },
    new DataFilter() { Id = 14, Values = "14", Name = "Denmark", Indent = 1, IsSelected = false },
    new DataFilter() { Id = 15, Values = "15", Name = "Finland", Indent = 1, IsSelected = false },

DataDashboardWeb/Pages/Cancelled.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DataDashboardWeb.Pages
{
    public class CancelledModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

DataDashboardWeb/Pages/CommunicationsPreferences.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using DataDashboardWebLib;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;

namespace DataDashboardWeb.Pages
{
    public class CommunicationsPreferencesModel : PageModel
    {
        [BindProperty]
        public CommunicationsPreferencesFormModel CommunicationsPreferencesForm { get; set; }

        private readonly AppSettings _appSettings;

        public CommunicationsPreferencesModel(IOptions<AppSettings> appSettings)
        {
            _appSettings = appSettings.Value;
        }

        public IActionResult OnGet()
        {
            // Get our authentication token from session state
            var token = HttpContext.Session.GetString("Token");

            // If there is no token then send to login
            if (token == null)
            {
                return Redirect("/Login");
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            // Get our authentication token from session state
            var token = HttpContext.Session.GetString("Token");

            string apiUrl = _appSettings.ApiUrl;

            // NOTE //////////////////////////////////////////////////////////////////////////////
            // This a bit messy, get the user and then get the Id separately!!
            // Get the user's account information
            UserAccess userAccess = new UserAccess(apiUrl, token);
            var user = await userAccess.GetUser();

            // NOTE //////////////////////////////////////////////////////////////////////////////
            // Get the User ID - DO NOT LIKE THIS!!!!
            // Would prefer not to pass the id and have it handled in the API using authentication
            // Or inside the Class Library (DataDashboardWebLib)
            string userId = await userAccess.GetUserId(user.Email);

            // Get the user's current subscription
            SubscriptionAccess subscriptionAccess = new SubscriptionAccess(apiUrl, token);
            Subscription subscription = await subscriptionAccess.GetSubscription(userId);

            // Now, set the communication preferences
            await subscriptionAccess.SetSubscriptionIsCommsOkay(subscription.SubscriptionId, CommunicationsPreferencesForm.IsOkay);

            return Redirect("/Dashboard/Home");
        }
    }

    public class CommunicationsPreferencesFormModel
    {
        [Required(ErrorMessage = "Please select one of the two options")]
        public bool IsOkay { get; set; }
    }
}

DataDashboardWeb/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Options;
using System.IO;
using System.ComponentModel.DataAnnotations;
using DataDashboardMessagingLibCore;
using DataDashboardWebLib;
using DataDashboardMessagingLibCore.Models;

namespace DataDashboardWeb.Pages
{
    public class ContactModel : PageModel
    {
        [BindProperty]
        public PublicContactFormModel ContactForm { get; set; }

        public string SuccessMessage { get; set; }
        public string ErrorMessage { get; set; }

        private readonly AppSettings _appSettings;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IDistributedCache _distributedCache;

        public ContactModel(IOptions<AppSettings> appSettings, IHostingEnvironment hostingEnvironment, IDistributedCache distributedCache)
        {
            _appSettings = appSettings.Value;
            _hostingEnvironment = hostingEnvironment;
            _distributedCache = distributedCache;
        }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostAsync()
        {
            // Create an email using the form data
            string azureStorageConnection = _appSettings.AzureStorageConnection; // Get the connection string for Azure Storage Queues
            string reCaptchaKey = _appSettings.reCaptchaSecretKey; // Get reCAPTCHA secret key

            // Get values for use by reCAPTCHA
            string recaptchaResponse = Request.Form["g-recaptcha-response"]; // Hidden field
            string usersIPAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString(); // User's IP address

            // Get data from our form
            string firstName = ContactForm.FirstName;
            string lastName = ContactForm.LastName;
            string email = ContactForm.Email;
            string message = ContactForm.EnquiryText;

            // Path to the email template
            string webRootPath = _hostingEnvironment.WebRootPath;
            string emailTemplatePath = webRootPath + Path.DirectorySeparatorChar.ToString()
                                        + "templates" + Path.DirectorySeparatorChar.ToString()
                                        + "email" + Path.DirectorySeparatorChar.ToString()
                                        + "PublicContactFormMessage.html";

            // This is our transaction helper
            TransactionAccess transactionAccess = new TransactionAccess(""); // Expects an API URL but we don't need it in this case

            // Validate the reCAPTCHA widget, if fails then show message and stop
            ReCaptchaResult recaptchaResult = await transactionAccess.ValidateReCaptcha(reCaptchaKey, recaptchaResponse, usersIPAddress);
            if (recaptchaResult.IsSuccess == false)
            {
                ErrorMessage = recaptchaResult.ErrorMessage;
                return Page();
            }

            try
            {
                // Email time
                EmailAccess emailAccess = new EmailAccess(azureStorageConnection);

                // Create the email content
                string body = emailAccess.CreateMessageBody(emailTemplatePath, firstName, lastName, email, message);

                // Create the outgoing email object
                OutgoingEmail outgoingEmail = emailAccess.CreateOutgoingEmail("help@discoveredinsights.com", email, "Public Contact Form Submission", body);

                // Send the email
                await emailAccess.Send(outgoingEmail);

                SuccessMessage = "Thank you for your message";
            }
            catch (Exception ex)
            {
                ErrorMessage = "Sorry, something went wrong and your message was not sent";
            }

            return Page();
        }
    }
    public class PublicContactFormModel
    {
        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Message")]
        public string EnquiryText { get; set; }

        [Required]
        [Display(Name = "reCAPTCHA")]
        public string ReCaptcha { get; set; }
    }
}

DataDashboardWeb/Pages/ApplyFilters.cshtml
@page
@model DataDashboardWeb.Pages.ApplyFiltersModel
@{
    Layout = null;
}

@Model.Message

@if (String.IsNullOrEmpty(Model.Message) == true)
{

    <form method="post">
        <input type="hidden" id="postbackPage" name="postbackPage" value="" />
        <div id="filtersModal" class="modal fade" role="dialog">
            <div class="modal-dialog modal-lg">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Apply Filters</h4>
                    </div>
                    <div class="modal-body">

                        <p>Select from the following to filter ALL data in the dashboard.</p>

                        <div class="row">
                            <div class="col-md-3">

                                <h4>Geography</h4>
                                <div class="scroll-area">
                                    @foreach (var geography in Model.Geographies)
                                    {
                                        <div class="checkbox chk-indent-@geography.Indent">
                                            <label>
                                                <input type="checkbox" name="chkgeography" value="@geography.Id"
                                                       @(geography.IsSelected == true ? "checked=\"checked\"" : String.Empty )>@geography.Name
                                                </label>
                                            </div>
                                        }
                                </div>

                            </div>
                            <div class="col-md-4">

                                <h4>Company Size</h4>
                                <div class="scroll-area">
                                    @foreach (var companySize in Model.CompanySizes)
                                    {
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox" name="chkcompanysize" value="@companySize.Id"
                                                       @(companySize.IsSelected == true ? "checked=\"checked\"" : String.Empty )>@companySize.Name
                                                </label>
                                            </div>
                                        }
                                </div>

                            </div>
                            <div class="col-md-5">

                                <h4>Industry</h4>
                                <div class="scroll-area">
                                    @foreach (var industry in Model.Industries)
                                    {
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox" name="chkindustry" value="@industry.Id"
                                                       @(industry.IsSelected == true ? "checked=\"checked\"" : String.Empty )>@industry.Name
                                                </label>
                                            </div>
                                        }
                                </div>

                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-default" asp-page-handler="apply">Apply</button>
                        <button type="submit" class="btn btn-default" asp-page-handler="clear">Clear All</button>
                    </div>
                </div>

            </div>
        </div>
    </form>

}

<script>

    $(function () {
        $('#postbackPage').val(window.location.pathname);
    });

</script>

DataDashboardWeb/Pages/Cancelled.cshtml
@page
@model DataDashboardWeb.Pages.CancelledModel
@{
    ViewData["Title"] = "Cancelled";
    ViewData["MetaDescription"] = "We are sorry that you have decided to cancel your subscription and hope that you will come back again.";
}

<div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8">
        <h1>Sorry</h1>
    </div>
    <div class="col-md-2">
    </div>
</div>
<div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8">
        <h3>We are sorry that you have decided to cancel your subscription and hope that you will come back again.</h3>
    </div>
    <div class="col-md-2">
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DataDashboardWeb/Pages/CommunicationsPreferences.cshtml
@page
@model DataDashboardWeb.Pages.CommunicationsPreferencesModel
@{
    ViewData["Title"] = "Communication Preferences";
    ViewData["MetaDescription"] = "Opt in or out of communications from Discovered Insights.";
}

<div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
        <h2>Communication Preferences</h2>
    </div>
    <div class="col-md-3">
    </div>
</div>
<div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">

        <p>We would like to send you emails such as notifications about new features, special offers, or additional insights.</p>
        <p>Please let us know if you would like to receive these emails by selecting from the following two options.</p>

        <form method="post">

            <div class="form-group">

                <div>
                    <div class="radio">
                        <label>
                            <input type="radio" asp-for="CommunicationsPreferencesForm.IsOkay" value="true" />
                            Yes, I would like to receive these emails
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio" asp-for="CommunicationsPreferencesForm.IsOkay" value="false" />
                            No, I would prefer not to receive these emails
                        </label>
                    </div>
                </div>

                <span class="label label-warning" asp-validation-for="CommunicationsPreferencesForm.IsOkay"></span>

            </div>

            <div class="form-group">
                <div>
                    <button type="submit" class="btn btn-default">Save preferences</button>
                </div>
            </div>

        </form>

        <p><small>You can change your preference at any time by going to your "Account" in the portal. This does not include emails concerning your subscription such as renewals.</small></p>

    </div>
    <div class="col-md-3">
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DataDashboardWeb/Pages/Contact.cshtml
@page
@model DataDashboardWeb.Pages.ContactModel
@{
    ViewData["Title"] = "Contact";
    ViewData["MetaDescription"] = "Contact us if you have any comments or questions.";
}

<h2>Contact</h2>

@if (string.IsNullOrWhiteSpace(Model.SuccessMessage) == false)
{
    <div class="alert alert-success" role="alert">@Model.SuccessMessage</div>
}
@if (string.IsNullOrWhiteSpace(Model.ErrorMessage) == false)
{
    <div class="alert alert-danger" role="alert">@Model.ErrorMessage</div>
}

<form method="post" class="form-horizontal">

    <div class="row">
        <div class="col-md-7">

            <div class="well bs-component">

                <fieldset>
                    @*<legend>Your Details</legend>*@

                    <div class="form-group">
                        <label asp-for="ContactForm.FirstName" class="col-lg-2 control-label">First Name</label>
                        <div class="col-lg-10">
                            <input type="text" asp-for="ContactForm.FirstName" class="form-control" placeholder="First Name">
                            <span class="label label-warning" asp-validation-for="ContactForm.FirstName"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="ContactForm.LastName" class="col-lg-2 control-label">Last Name</label>
                        <div class="col-lg-10">
                            <input type="text" asp-for="ContactForm.LastName" class="form-control" placeholder="Last Name">
                            <span class="label label-warning" asp-validation-for="ContactForm.LastName"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="ContactForm.Email" class="col-lg-2 control-label">Email</label>
                        <div class="col-lg-10">
                            <input type="email" asp-for="ContactForm.Email" class="form-control" placeholder="Email">
                            <span class="label label-warning" asp-validation-for="ContactForm.Email"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="ContactForm.EnquiryText" class="col-lg-2 control-label">Message</label>
                        <div class="col-lg-10">
                            <textarea class="form-control" asp-for="ContactForm.EnquiryText" rows="3"></textarea>
                            <span class="label label-warning" asp-validation-for="ContactForm.EnquiryText"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-10 col-lg-offset-2">
                            <div id="reCaptchaDiv"></div>
                            <div style="height: 0px; display: block; overflow: hidden;"><input type="text" asp-for="ContactForm.ReCaptcha" /></div>
                            <span class="label label-warning" asp-validation-for="ContactForm.ReCaptcha"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-10">
                            <button type="submit" class="btn btn-default">Submit</button>
                        </div>
                    </div>

                </fieldset>

            </div>

        </div>
        <div class="col-md-5">

            <p>To express an interest in subscribing, ask a question or send us a comment please complete this form.</p>
            <p>We endeavour to respond as quickly as possible.</p>
            <p>&nbsp;</p>
            <p><strong>Please note, all fields are mandatory.</strong></p>

        </div>
    </div>

</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src='https://www.google.com/recaptcha/api.js?onload=captchaOnloadCallback&render=explicit'></script>

    <script>

        $(function () { // Set the appropriate nav item to active
            $($(".nav").find("li").get(2)).addClass("active");
        });

        // reCAPTCHA ///////////////////////////////////////////////////////////////////////////////////////////
        // Here we are setting up the reCAPTCHA and assigning a function that will run when the box is checked
        var captchaOnloadCallback = function () {
            grecaptcha.render('reCaptchaDiv', {
                'sitekey': '6LcmSjkUAAAAAFNQMn43TjbnqNUqSOzrb4duyon9',
                'callback': correctCaptcha
            });
        };

        var correctCaptcha = function (response) {
            $("#ContactForm_ReCaptcha").val(response);
        };
        ////////////////////////////////////////////////////////////////////////////////////////////////////////

    </script>
}

DataDashboardWeb/Pages/HowTo.cshtml
@page
@model DataDashboardWeb.Pages.HowToModel
@{
    ViewData["Title"] = "How To... get the most from Discovered Insights";
    ViewData["MetaDescription"] = "Watch this video to see how you can get the most from a Discovered Insights subscription.";
}

<h2>How To... get the most from Discovered Insights</h2>

<hr />

<div class="row">
    <div class="col-md-8">

        <video id="howtoVideo" width="90%" controls>
            <source src="~/video/get-the-most-from-discovered-insights.mp4" type="video/mp4">
            Browser does not support video tag
        </video>

    </div>
    <div class="col-md-4">

        <p class="lead">In this video we explore 3 common ways in which you can use Discovered Insights in order to help your organisation.</p>
        <p class="lead">If you have any questions about Discovered Insights please <a href="/Contact">contact us</a>.</p>

    </div>
</div>