DataDashboardWeb/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Options;
using System.IO;
using System.ComponentModel.DataAnnotations;
using DataDashboardMessagingLibCore;
using DataDashboardWebLib;
using DataDashboardMessagingLibCore.Models;

namespace DataDashboardWeb.Pages
{
    public class ContactModel : PageModel
    {
        [BindProperty]
        public PublicContactFormModel ContactForm { get; set; }

        public string SuccessMessage { get; set; }
        public string ErrorMessage { get; set; }

        private readonly AppSettings _appSettings;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IDistributedCache _distributedCache;

        public ContactModel(IOptions<AppSettings> appSettings, IHostingEnvironment hostingEnvironment, IDistributedCache distributedCache)
        {
            _appSettings = appSettings.Value;
            _hostingEnvironment = hostingEnvironment;
            _distributedCache = distributedCache;
        }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostAsync()
        {
            // Create an email using the form data
            string azureStorageConnection = _appSettings.AzureStorageConnection; // Get the connection string for Azure Storage Queues
            string reCaptchaKey = _appSettings.reCaptchaSecretKey; // Get reCAPTCHA secret key

            // Get values for use by reCAPTCHA
            string recaptchaResponse = Request.Form["g-recaptcha-response"]; // Hidden field
            string usersIPAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString(); // User's IP address

            // Get data from our form
            string firstName = ContactForm.FirstName;
            string lastName = ContactForm.LastName;
            string email = ContactForm.Email;
            string message = ContactForm.EnquiryText;

            // Path to the email template
            string webRootPath = _hostingEnvironment.WebRootPath;
            string emailTemplatePath = webRootPath + Path.DirectorySeparatorChar.ToString()
                                        + "templates" + Path.DirectorySeparatorChar.ToString()
                                        + "email" + Path.DirectorySeparatorChar.ToString()
                                        + "PublicContactFormMessage.html";

            // This is our transaction helper
            TransactionAccess transactionAccess = new TransactionAccess(""); // Expects an API URL but we don't need it in this case

            // Validate the reCAPTCHA widget, if fails then show message and stop
            ReCaptchaResult recaptchaResult = await transactionAccess.ValidateReCaptcha(reCaptchaKey, recaptchaResponse, usersIPAddress);
            if (recaptchaResult.IsSuccess == false)
            {
                ErrorMessage = recaptchaResult.ErrorMessage;
                return Page();
            }

            try
            {
                // Email time
                EmailAccess emailAccess = new EmailAccess(azureStorageConnection);

                // Create the email content
                string body = emailAccess.CreateMessageBody(emailTemplatePath, firstName, lastName, email, message);

                // Create the outgoing email object
                OutgoingEmail outgoingEmail = emailAccess.CreateOutgoingEmail("help@discoveredinsights.com", email, "Public Contact Form Submission", body);

                // Send the email
                await emailAccess.Send(outgoingEmail);

                SuccessMessage = "Thank you for your message";
            }
            catch (Exception ex)
            {
                ErrorMessage = "Sorry, something went wrong and your message was not sent";
            }

            return Page();
        }
    }
    public class PublicContactFormModel
    {
        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Message")]
        public string EnquiryText { get; set; }

        [Required]
        [Display(Name = "reCAPTCHA")]
        public string ReCaptcha { get; set; }
    }
}

DataDashboardWeb/Pages/Dashboard/Account.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;
using DataDashboardWebLib;

namespace DataDashboardWeb.Pages.Dashboard
{
    public class AccountModel : PageModel
    {
        [BindProperty]
        public AccountDetailsModel AccountForm { get; set; }

        [BindProperty]
        public ChangePasswordModel ChangePasswordForm { get; set; }

        [BindProperty]
        public CommunicationPreferencesModel CommunicationPreferencesForm { get; set; }

        public string SubscriptionDaysRemaining { get; set; }
        public string SubscriptionReference { get; set; }
        public string SuccessMessage { get; set; }
        public string ErrorMessage { get; set; }

        private readonly AppSettings _appSettings;

        public AccountModel(IOptions<AppSettings> appSettings)
        {
            _appSettings = appSettings.Value;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            // Get our authentication token from session state
            var token = HttpContext.Session.GetString("Token");

            // If there is no token then send to login
            if (token == null)
            {
                return Redirect("/Login");
            }

            string apiUrl = _appSettings.ApiUrl;

            // Get the user's account information
            UserAccess userAccess = new UserAccess(apiUrl, token);
            var user = await userAccess.GetUser();
            
            // Now populate the account form fields
            AccountForm = new AccountDetailsModel
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email
            };

            // NOTE //////////////////////////////////////////////////////////////////////////////
            // Get the User ID - DO NOT LIKE THIS!!!!
            // Would prefer not to pass the id and have it handled in the API using authentication
            // Or inside the Class Library (DataDashboardWebLib)
            string userId = await userAccess.GetUserId(user.Email);

            // Now, look up the subscription
            SubscriptionAccess subscriptionAccess = new SubscriptionAccess(apiUrl, token);
            Subscription subscription = await subscriptionAccess.GetSubscription(userId);

            SubscriptionDaysRemaining = Math.Round((subscription.EndDate - DateTime.Now).TotalDays).ToString(); // How long left on this subscription
            SubscriptionReference = subscription.SubscriptionReference; // Get the reference number

            CommunicationPreferencesForm = new CommunicationPreferencesModel
            {
                IsOkay = subscription.IsCommsOkay
            };

            return Page();
        }

        public async Task<IActionResult> OnPostUpdateAsync()
        {
            // Update personal details
            // Get our authentication token from session state
            var token = HttpContext.Session.GetString("Token");

            string apiUrl = _appSettings.ApiUrl;

            // Update the user's details
            UserAccess userAccess = new UserAccess(apiUrl, token);
            bool isResult = await userAccess.UpdateUser(AccountForm.Email, AccountForm.FirstName, AccountForm.LastName);

            if (isResult)
            {
                SuccessMessage = "Update Successful";
            }
            else
            {
                ErrorMessage = "Update Unsuccessful";
            }

            return Page();
        }

        public async Task<IActionResult> OnPostChangepasswordAsync()
        {
            // Get our authentication token from session state
            var token = HttpContext.Session.GetString("Token");

            string apiUrl = _appSettings.ApiUrl;

            // Change the user's password
            UserAccess userAccess = new UserAccess(apiUrl, token);
            bool isResult = await userAccess.ChangePassword(ChangePasswordForm.Password, ChangePasswordForm.NewPassword);

            if (isResult)
            {
                SuccessMessage = "Password Change Successful";
            }
            else
            {
                ErrorMessage = "Password Change Unsuccessful";
            }

            return Page();
        }

        public async Task<IActionResult> OnPostCancelAsync()
        {
            // Get our authentication token from session state
            var token = HttpContext.Session.GetString("Token");

            string apiUrl = _appSettings.ApiUrl;

            // NOTE //////////////////////////////////////////////////////////////////////////////
            // This a bit messy, get the user and then get the Id separately!!
            // Get the user's account information
            UserAccess userAccess = new UserAccess(apiUrl, token);
            var user = await userAccess.GetUser();

            // NOTE //////////////////////////////////////////////////////////////////////////////
            // Get the User ID - DO NOT LIKE THIS!!!!
            // Would prefer not to pass the id and have it handled in the API using authentication
            // Or inside the Class Library (DataDashboardWebLib)
            string userId = await userAccess.GetUserId(user.Email);

            // Now, look up the subscription
            SubscriptionAccess subscriptionAccess = new SubscriptionAccess(apiUrl, token);
            Subscription subscription = await subscriptionAccess.GetSubscription(userId);

            // De-activate the subscription
            await subscriptionAccess.SetSubscriptionIsActive(subscription.SubscriptionId, false);

            // Delete the user
            await userAccess.Delete();

            // Now, clear the session
            HttpContext.Session.Clear();

            return Redirect("/Index");
        }

        public async Task<IActionResult> OnPostSavepreferencesAsync()
        {
            // Get our authentication token from session state
            var token = HttpContext.Session.GetString("Token");

            string apiUrl = _appSettings.ApiUrl;

            // NOTE //////////////////////////////////////////////////////////////////////////////
            // This a bit messy, get the user and then get the Id separately!!
            // Get the user's account information
            UserAccess userAccess = new UserAccess(apiUrl, token);
            var user = await userAccess.GetUser();

            // NOTE //////////////////////////////////////////////////////////////////////////////
            // Get the User ID - DO NOT LIKE THIS!!!!
            // Would prefer not to pass the id and have it handled in the API using authentication
            // Or inside the Class Library (DataDashboardWebLib)
            string userId = await userAccess.GetUserId(user.Email);

            // Get the user's current subscription
            SubscriptionAccess subscriptionAccess = new SubscriptionAccess(apiUrl, token);
            Subscription subscription = await subscriptionAccess.GetSubscription(userId);

            // Now, set the communication preferences
            bool isResult = await subscriptionAccess.SetSubscriptionIsCommsOkay(subscription.SubscriptionId, CommunicationPreferencesForm.IsOkay);

            if (isResult)
            {
                SuccessMessage = "Preferences Saved Successfully";
            }
            else
            {
                ErrorMessage = "Preferences Saved Unsuccessfully";
            }

            return Page();
        }
    }

    public class AccountDetailsModel
    {
        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Required]
        public string Email { get; set; }
    }

    public class ChangePasswordModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string Password { get; set; }

        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{6,15}$", ErrorMessage = "Must contain 1 upper case, 1 lower case and 1 number")]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }
    }

    public class CommunicationPreferencesModel
    {
        [Required(ErrorMessage = "Please select one of the two options")]
        public bool IsOkay { get; set; }
    }
}

DataDashboardWeb/Pages/Dashboard/AllTopics.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;

namespace DataDashboardWeb.Pages.Dashboard
{
    public class AllTopicsModel : PageModel
    {
        private readonly AppSettings _appSettings;

        public AllTopicsModel(IOptions<AppSettings> appSettings)
        {
            _appSettings = appSettings.Value;
        }

        public IActionResult OnGet()
        {
            // Get our authentication token from session state
            var token = HttpContext.Session.GetString("Token");

            // If there is no token then send to login
            if (token == null)
            {
                return Redirect("/Login");
            }

            return Page();
        }
    }
}

DataDashboardWeb/Pages/Dashboard/FirstTime.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;

namespace DataDashboardWeb.Pages.Dashboard
{
    public class FirstTimeModel : PageModel
    {
        private readonly AppSettings _appSettings;

        public FirstTimeModel(IOptions<AppSettings> appSettings)
        {
            _appSettings = appSettings.Value;
        }

        public IActionResult OnGet()
        {
            // Get our authentication token from session state
            var token = HttpContext.Session.GetString("Token");

            // If there is no token then send to login
            if (token == null)
            {
                return Redirect("/Login");
            }

            return Page();
        }
    }
}

DataDashboardWeb/Pages/Dashboard/Home.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Http;
using DataDashboardWebLib;

namespace DataDashboardWeb.Pages.Dashboard
{
    public class HomeModel : PageModel
    {
        public string FirstName { get; set; }

        private readonly AppSettings _appSettings;

        public HomeModel(IOptions<AppSettings> appSettings)
        {
            _appSettings = appSettings.Value;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            // Get our authentication token from session state
            var token = HttpContext.Session.GetString("Token");

            // If there is no token then send to login
            if (token == null)
            {
                return Redirect("/Login");
            }

            string apiUrl = _appSettings.ApiUrl;

            // Get the user's account information in order to get their first name :)
            UserAccess userAccess = new UserAccess(apiUrl, token);
            var user = await userAccess.GetUser();

            FirstName = user.FirstName;

            return Page();
        }
    }
}

DataDashboardWeb/Pages/Dashboard/Account.cshtml
@page
@model DataDashboardWeb.Pages.Dashboard.AccountModel
@{
    ViewData["Title"] = "Account";
    Layout = "~/Pages/_DashboardLayout.cshtml";
}

<h2>Account</h2>

@if (string.IsNullOrWhiteSpace(Model.SuccessMessage) == false)
{
    <div class="alert alert-success" role="alert">@Model.SuccessMessage</div>
}
@if (string.IsNullOrWhiteSpace(Model.ErrorMessage) == false)
{
    <div class="alert alert-danger" role="alert">@Model.ErrorMessage</div>
}

<div class="row">
    <div class="col-md-6">

        <div class="panel panel-default">
            <div class="panel-heading">Your Details</div>
            <div class="panel-body">

                <form method="post">

                    <div class="form-group">
                        <label asp-for="AccountForm.FirstName">First Name</label>
                        <input type="text" asp-for="AccountForm.FirstName" class="form-control" placeholder="First Name">
                        <span class="label label-warning" asp-validation-for="AccountForm.FirstName"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="AccountForm.LastName">Last Name</label>
                        <input type="text" asp-for="AccountForm.LastName" class="form-control" placeholder="Last Name">
                        <span class="label label-warning" asp-validation-for="AccountForm.LastName"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="AccountForm.Email">Email</label>
                        <input type="email" asp-for="AccountForm.Email" class="form-control" placeholder="Email">
                        <span class="label label-warning" asp-validation-for="AccountForm.Email"></span>
                    </div>

                    <button type="submit" class="btn btn-default" asp-page-handler="update">Update</button>

                </form>

            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">Change Password</div>
            <div class="panel-body">

                <form method="post">

                    <div class="form-group">
                        <label asp-for="ChangePasswordForm.Password">Current Password</label>
                        <input type="password" asp-for="ChangePasswordForm.Password" class="form-control" placeholder="Current Password">
                        <span class="label label-warning" asp-validation-for="ChangePasswordForm.Password"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="ChangePasswordForm.NewPassword">New Password</label>
                        <input type="password" asp-for="ChangePasswordForm.NewPassword" class="form-control" placeholder="New Password">
                        <span class="label label-warning" asp-validation-for="ChangePasswordForm.NewPassword"></span>
                        <span class="help-block">
                            Passwords must be between 6 and 15 characters and contain:
                            <br />1 upper case letter
                            <br />1 lower case letter
                            <br />1 number
                        </span>
                    </div>

                    <button type="submit" class="btn btn-default" asp-page-handler="changepassword">Change</button>

                </form>

            </div>
        </div>

    </div>
    <div class="col-md-6">

        <div class="panel panel-default">
            <div class="panel-heading">Your Subscription</div>
            <div class="panel-body">

                <form method="post">
                    <p>Your subscription <b>@Model.SubscriptionReference</b> expires in <b>@Model.SubscriptionDaysRemaining days</b>.</p>
                    <p>You can cancel your subscription at any time and all of personal information held by Discovered Insights will be deleted. Please note that cancelling does not result in any money being refunded.</p>

                    <button type="submit" class="btn btn-default" asp-page-handler="cancel">Cancel</button>
                </form>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">Communication Preferences</div>
            <div class="panel-body">

                <form method="post">
                    <p>We would like to send you emails such as notifications about new features, special offers, or additional insights.</p>
                    <p>Please let us know if you would like to receive these emails by selecting from the following two options.</p>

                    <div class="form-group">

                        <div class="radio">
                            <label>
                                <input type="radio" asp-for="CommunicationPreferencesForm.IsOkay" value="true" />
                                Yes, I would like to receive these emails
                            </label>
                        </div>
                        <div class="radio">
                            <label>
                                <input type="radio" asp-for="CommunicationPreferencesForm.IsOkay" value="false" />
                                No, I would prefer not to receive these emails
                            </label>
                        </div>

                        <span class="label label-warning" asp-validation-for="CommunicationPreferencesForm.IsOkay"></span>

                    </div>

                    <button type="submit" class="btn btn-default" asp-page-handler="savepreferences">Save</button>

                    <p><small><br/>This does not include emails concerning your subscription such as renewals.</small></p>
                </form>
            </div>
        </div>

    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
    $(function () { // Set the appropriate nav item to active
        $($(".nav:nth-child(2)").find("li").get(2)).addClass("active");
    });
    </script>
}

DataDashboardWeb/Pages/Dashboard/Contact.cshtml
@page
@model DataDashboardWeb.Pages.Dashboard.ContactModel
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Pages/_DashboardLayout.cshtml";
}

<h2>Contact</h2>

@if (string.IsNullOrWhiteSpace(Model.SuccessMessage) == false)
{
    <div class="alert alert-success" role="alert">@Model.SuccessMessage</div>
}
@if (string.IsNullOrWhiteSpace(Model.ErrorMessage) == false)
{
    <div class="alert alert-danger" role="alert">@Model.ErrorMessage</div>
}

<form method="post" class="form-horizontal">

    <input type="hidden" asp-for="ContactForm.SubscriptionReference" />

    <div class="row">
        <div class="col-md-7">

            <div class="well bs-component">

                <fieldset>
                    @*<legend>Your Details</legend>*@

                    <div class="form-group">
                        <label asp-for="ContactForm.FirstName" class="col-lg-2 control-label">First Name</label>
                        <div class="col-lg-10">
                            <input type="text" asp-for="ContactForm.FirstName" class="form-control" placeholder="First Name">
                            <span class="label label-warning" asp-validation-for="ContactForm.FirstName"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="ContactForm.LastName" class="col-lg-2 control-label">Last Name</label>
                        <div class="col-lg-10">
                            <input type="text" asp-for="ContactForm.LastName" class="form-control" placeholder="Last Name">
                            <span class="label label-warning" asp-validation-for="ContactForm.LastName"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="ContactForm.Email" class="col-lg-2 control-label">Email</label>
                        <div class="col-lg-10">
                            <input type="email" asp-for="ContactForm.Email" class="form-control" placeholder="Email">
                            <span class="label label-warning" asp-validation-for="ContactForm.Email"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="ContactForm.EnquiryText" class="col-lg-2 control-label">Message</label>
                        <div class="col-lg-10">
                            <textarea class="form-control" asp-for="ContactForm.EnquiryText" rows="3"></textarea>
                            <span class="label label-warning" asp-validation-for="ContactForm.EnquiryText"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-10">
                            <button type="submit" class="btn btn-default">Submit</button>
                        </div>
                    </div>

                </fieldset>

            </div>

        </div>
        <div class="col-md-5">

            <p>To ask a question or send us a comment please complete this form.</p>
            <p>We endeavour to respond as quickly as possible.</p>
            <p>&nbsp;</p>
            <p><strong>Please note, all fields are mandatory.</strong></p>

        </div>
    </div>

</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

<script>
    $(function () { // Set the appropriate nav item to active
        $($(".nav:nth-child(2)").find("li").get(1)).addClass("active");
    });
</script>
}

DataDashboardWeb/Pages/Dashboard/FirstTime.cshtml
@page
@model DataDashboardWeb.Pages.Dashboard.FirstTimeModel
@{
    ViewData["Title"] = "First Time Guide";
    Layout = "~/Pages/_DashboardLayout.cshtml";
}

<h2>First Time Guide</h2>

<p>First time visitors may find the following information useful.</p>

<div class="row" style="margin-bottom: 15px;">
    <div class="col-md-4">

        <h4>Topic areas</h4>
        <p>
            All data is grouped into Topic Areas. Select one from the dropdown (above, next to the Discovered Insights logo) to view the data available in that topic. The Companion Report is structured into these same Topic Areas for easy reference.
        </p>

    </div>
    <div class="col-md-4">

        <h4>Datasets</h4>
        <p>
            When viewing a Topic Area (or dataset) you will see a dropdown of datasets. Select a dataset in order to view its data and charts.
        </p>

    </div>
    <div class="col-md-4">

        <h4>Download charts</h4>
        <p>
            All charts can be downloaded as images. These can be placed in presentations and documents, and resized as required. Downloaded charts will reflect any applied filters.
        </p>
        <p><small>Downloading charts works on mobile devices however we recommend using devices with larger screens.</small></p>

    </div>
</div>

<div class="row">
    <div class="col-md-4">

        <h4>Filters</h4>
        <p>
            Data can be filtered by geography, industry and company size. Simply click on the 'Filter' option at the top of the screen. Any filter selections will then be applied to all datasets until they are changed, cleared or the next time you visit Discovered Insights.
        </p>
        <p><small>Applying filters reduces the volume of data available to each dataset. In some cases there may be no data available for certain datasets.</small></p>

    </div>
    <div class="col-md-4">

        <h4>Listen to insights</h4>
        <p>
            Click on the "Listen to insights" button to listen to the appropriate Topic Area insights from the "Discovered Insights 2018 Companion Report: Understanding Digital Transformation".
        </p>

    </div>
    <div class="col-md-4">

        <h4>Need help?</h4>
        <p>
            If you experience problems viewing data please click on 'Contact' at the top of the screen and send us a help request. We will endeavour to reply within 24 hours or the next working day.
        </p>

    </div>
</div>

DataDashboardWeb/Pages/Dashboard/Logout.cshtml
@page
@model DataDashboardWeb.Pages.Dashboard.LogoutModel
@{
    ViewData["Title"] = "Logout";
    Layout = "~/Pages/_DashboardLayout.cshtml";
}